#!/usr/bin/env python3
"""Generate compact MoP Classic item-to-expansion correction ranges.

MoP Classic's ItemSparse expansion field is 254, so the addon cannot use it
to separate expansion profiles. The Blizzard client Item DB2 tables exposed by
Wago Tools let us determine an item's era by the first Classic client line in
which its ID appears.
"""

from __future__ import annotations

import argparse
import csv
import subprocess
import tempfile
from pathlib import Path


BUILDS = (
    (0, "Classic", "1.14.3.44834"),
    (1, "The Burning Crusade", "2.5.4.44833"),
    (2, "Wrath of the Lich King", "3.4.3.52237"),
    (3, "Cataclysm", "4.4.2.60895"),
    (4, "Mists of Pandaria", "5.5.4.68806"),
)

SOURCE_URL = "https://wago.tools/db2/Item/csv?build={build}"
SENTINELS = {
    4306: 0,   # Silk Cloth
    22645: 1,  # Crunchy Spider Surprise
    33470: 2,  # Frostweave Cloth
    53010: 3,  # Embersilk Cloth
    72988: 4,  # Windwool Cloth
}


def read_ids(path: Path) -> set[int]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return {int(row["ID"]) for row in csv.DictReader(handle)}


def threshold_expansion(item_id: int) -> int:
    if item_id >= 72000:
        return 4
    if item_id >= 52000:
        return 3
    if item_id >= 33000:
        return 2
    if item_id >= 21800:
        return 1
    return 0


def correction_ranges(corrections: list[tuple[int, int]]) -> list[tuple[int, int, int]]:
    ranges: list[tuple[int, int, int]] = []
    for item_id, expansion_id in corrections:
        if ranges and ranges[-1][2] == expansion_id and item_id == ranges[-1][1] + 1:
            start, _, expansion = ranges[-1]
            ranges[-1] = (start, item_id, expansion)
        else:
            ranges.append((item_id, item_id, expansion_id))
    return ranges


def range_lookup(ranges: list[tuple[int, int, int]], item_id: int) -> int | None:
    low = 0
    high = len(ranges) - 1
    while low <= high:
        middle = (low + high) // 2
        start, finish, expansion_id = ranges[middle]
        if item_id < start:
            high = middle - 1
        elif item_id > finish:
            low = middle + 1
        else:
            return expansion_id
    return None


def download(build: str, destination: Path) -> None:
    subprocess.run(
        [
            "curl",
            "--location",
            "--fail",
            "--silent",
            "--show-error",
            "--max-time",
            "60",
            SOURCE_URL.format(build=build),
            "--output",
            str(destination),
        ],
        check=True,
    )


def render(ranges: list[tuple[int, int, int]]) -> str:
    build_text = ", ".join(f"{name} {build}" for _, name, build in BUILDS)
    lines = [
        "local _, GBO = ...",
        "",
        "-- Generated by scripts/generate_expansion_data.py from Blizzard client",
        "-- Item DB2 tables served by Wago Tools. Do not edit by hand.",
        f"-- Source builds: {build_text}",
        "-- Each row corrects an item-ID threshold where client generations overlap.",
        "local correctionRanges = {",
    ]
    lines.extend(
        f"    {{ {start}, {finish}, {expansion_id} }},"
        for start, finish, expansion_id in ranges
    )
    lines.extend(
        [
            "}",
            "",
            "function GBO:GetGeneratedDepositExpansion(itemID)",
            "    itemID = tonumber(itemID)",
            "    if not itemID then",
            "        return nil",
            "    end",
            "",
            "    local low = 1",
            "    local high = #correctionRanges",
            "    while low <= high do",
            "        local middle = math.floor((low + high) / 2)",
            "        local range = correctionRanges[middle]",
            "        if itemID < range[1] then",
            "            high = middle - 1",
            "        elseif itemID > range[2] then",
            "            low = middle + 1",
            "        else",
            "            return range[3]",
            "        end",
            "    end",
            "    return nil",
            "end",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "GuildBankOrganizer"
        / "ExpansionData.lua",
    )
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="gbo-expansion-data-") as directory:
        temp_dir = Path(directory)
        item_sets: list[set[int]] = []
        for _, _, build in BUILDS:
            path = temp_dir / f"Item.{build}.csv"
            download(build, path)
            item_sets.append(read_ids(path))

    first_expansion: dict[int, int] = {}
    for expansion_id, item_ids in enumerate(item_sets):
        for item_id in item_ids:
            first_expansion.setdefault(item_id, expansion_id)

    mop_item_ids = item_sets[-1]
    for item_id, expected in SENTINELS.items():
        actual = first_expansion.get(item_id)
        if actual != expected:
            raise RuntimeError(
                f"source validation failed for item {item_id}: {actual} != {expected}"
            )

    corrections = sorted(
        (item_id, first_expansion[item_id])
        for item_id in mop_item_ids
        if threshold_expansion(item_id) != first_expansion[item_id]
    )
    ranges = correction_ranges(corrections)

    for item_id in mop_item_ids:
        resolved = range_lookup(ranges, item_id)
        if resolved is None:
            resolved = threshold_expansion(item_id)
        if resolved != first_expansion[item_id]:
            raise RuntimeError(f"round-trip validation failed for item {item_id}")

    args.output.write_text(render(ranges), encoding="utf-8")
    print(
        f"wrote {args.output} with {len(ranges)} ranges "
        f"covering {len(corrections)} threshold corrections"
    )


if __name__ == "__main__":
    main()
